    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, END,
            W, _, X, X, X, _, W, END,
            W, _, _, _, _, _, W, END,
            W, _, P, U, A, _, W, END,
            W, _, _, _, _, _, W, END,
            W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0001 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, END,
            W, A, _, _, _, W, END,
            W, _, _, X, _, W, END,
            W, _, _, P, _, W, END,
            W, U, W, W, W, W, END,
            W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0002 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, W, W, W, W, END,
            _, W, _, _, _, _, _, _, W, END,
            W, W, _, X, _, X, P, _, W, END,
            W, R, _, _, _, _, _, _, W, END,
            W, W, _, _, _, _, _, _, W, W, END,
            _, W, _, _, _, _, _, _, L, W, END,
            _, W, _, A, X, _, X, _, W, W, END,
            _, W, _, _, _, _, _, _, W, END,
            _, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0003 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, _, _, W, W, W, W, W, END,
            W, _, _, _, W, W, W, W, _, _, _, W, END,
            W, _, X, _, _, X, _, _, _, X, _, W, END,
            W, _, _, _, W, W, W, W, _, _, _, W, END,
            W, W, _, _, W, _, _, W, _, _, W, W, END,
            _, W, _, A, W, W, W, W, P, _, W, END,
            _, W, _, _, D, W, W, D, _, _, W, END,
            _, W, _, _, B, _, _, B, _, _, W, END,
            _, W, _, _, B, _, _, B, _, _, W, END,
            _, W, W, _, B, _, _, B, _, W, W, END,
            _, _, W, W, _, _, _, _, W, W, END,
            _, _, _, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0004 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, END,
            W, X, _, _, _, X, W, END,
            W, _, D, _, L, _, W, END,
            W, _, _, A, _, _, W, END,
            W, _, R, _, U, _, W, END,
            W, X, _, P, _, X, W, END,
            W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0005 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, W, END,
            _, W, _, _, _, W, END,
            W, W, _, D, _, W, END,
            W, X, A, _, W, W, W, END,
            W, _, _, U, _, P, W, END,
            W, _, _, _, X, _, W, END,
            W, W, X, W, _, _, W, END,
            _, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0006 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, END,
            W, _, _, A, _, _, W, END,
            W, _, D, D, D, _, W, END,
            W, _, _, _, _, _, W, END,
            W, _, _, _, _, _, W, END,
            W, B, U, B, B, L, W, END,
            W, _, _, P, _, _, W, END,
            W, W, X, W, X, W, W, END,
            _, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0007 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, END,
            W, _, _, _, _, _, _, W, END,
            W, _, _, _, D, P, _, W, END,
            W, _, X, X, _, A, L, W, W, END,
            W, _, _, _, _, _, _, X, W, END,
            W, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0008 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, W, END,
            W, _, _, _, A, _, _, _, W, END,
            W, R, _, _, X, _, _, L, W, END,
            W, _, _, _, P, _, _, _, W, END,
            W, _, _, W, D, W, _, _, W, END,
            W, _, X, _, X, _, X, _, W, END,
            W, W, _, _, _, _, _, W, W, END,
            _, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0009 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, END,
            _, W, W, X, W, W, W, W, W, W, W, W, END,
            _, W, _, R, _, _, _, _, L, _, _, W, END,
            W, W, A, P, _, _, L, _, _, _, _, W, END,
            W, _, _, R, _, _, L, _, _, _, _, W, END,
            W, _, X, W, _, W, W, W, W, W, W, W, END,
            W, _, _, W, W, W, END,
            W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0010 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, W, END,
            W, _, _, _, _, X, B, P, W, END,
            W, _, _, U, _, W, X, X, W, END,
            W, _, _, _, _, X, W, X, W, END,
            W, _, _, _, _, _, _, _, W, END,
            W, _, _, _, _, _, R, _, W, END,
            W, R, A, _, _, _, _, _, W, END,
            W, _, U, _, _, _, _, _, W, END,
            W, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0011 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, END,
            _, _, W, _, X, _, W, END,
            W, W, W, _, P, _, W, W, W, END,
            W, _, _, B, _, B, _, _, W, END,
            W, X, _, R, _, L, _, X, W, END,
            W, _, _, B, _, B, _, _, W, END,
            W, W, W, _, A, _, W, W, W, END,
            _, _, W, _, _, _, W, END,
            _, _, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0012 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, W, END,
            W, _, _, _, _, _, _, _, W, END,
            W, _, X, _, _, _, _, _, W, W, W, W, END,
            W, _, _, _, _, _, _, _, _, _, _, W, END,
            W, _, X, _, _, _, _, _, _, _, _, W, END,
            W, _, _, U, U, U, R, _, _, _, _, W, END,
            W, W, W, W, W, W, R, _, _, _, _, W, END,
            _, _, _, _, _, W, R, _, _, X, _, W, END,
            _, _, _, _, _, W, _, P, X, _, A, W, END,
            _, _, _, _, _, W, _, X, X, X, _, W, END,
            _, _, _, _, _, W, _, _, _, _, W, W, END,
            _, _, _, _, _, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0013 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, W, W, END,
            W, W, _, D, _, _, W, END,
            W, X, _, B, _, X, W, END,
            W, X, P, X, A, X, W, END,
            W, X, _, B, _, X, W, END,
            W, _, _, U, _, W, W, END,
            W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0014 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, END,
            W, W, X, X, W, W, END,
            W, _, _, _, A, W, END,
            W, _, _, R, U, W, END,
            W, B, B, U, _, W, END,
            W, P, U, _, _, W, END,
            W, W, X, W, W, W, END,
            _, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0015 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, W, W, END,
            W, _, _, B, _, _, B, _, _, W, END,
            W, _, _, B, _, X, B, A, _, W, END,
            W, P, R, B, _, _, B, _, _, W, END,
            W, _, _, X, X, _, X, _, _, W, END,
            W, W, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0016 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, END,
            _, W, _, _, W, W, END,
            _, W, _, _, _, W, END,
            W, W, B, _, _, W, END,
            W, _, _, _, B, W, END,
            W, _, R, A, _, W, END,
            W, W, P, U, _, W, END,
            _, W, W, W, X, W, END,
            _, _, _, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0017 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, _, _, _, W, W, W, W, W, END,
            W, W, W, W, _, W, W, _, _, _, W, END,
            W, _, _, W, W, W, _, _, X, _, W, END,
            W, _, X, W, _, _, _, W, W, W, W, END,
            W, _, _, W, _, X, _, A, P, W, END,
            W, W, _, _, _, _, _, L, _, W, END,
            _, W, W, W, W, W, U, _, _, W, END,
            _, _, _, _, W, _, B, _, _, W, END,
            _, _, _, _, W, _, X, U, _, W, END,
            _, _, _, _, W, _, _, _, _, W, END,
            _, _, _, _, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0018 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, W, W, W, END,
            W, W, W, W, X, W, W, END,
            W, _, _, P, _, _, W, END,
            W, _, L, A, D, _, W, END,
            W, _, X, _, _, W, W, END,
            W, W, W, X, W, W, END,
            _, _, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0019 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, _, _, _, W, W, W, W, W, END,
            _, W, W, W, W, W, W, _, _, _, W, END,
            W, W, _, _, W, W, _, _, X, _, W, END,
            W, _, _, R, B, _, _, W, W, W, W, END,
            W, _, _, _, _, _, P, W, END,
            W, W, W, X, A, W, W, W, END,
            _, _, W, _, _, W, END,
            _, _, W, _, _, W, END,
            _, _, W, _, _, W, END,
            _, _, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0020 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, END,
            W, W, _, W, W, W, W, W, W, END,
            W, _, _, _, _, _, _, _, W, END,
            W, W, _, W, W, W, W, B, W, END,
            _, W, _, W, _, _, B, _, W, END,
            _, W, _, W, _, _, X, _, W, END,
            _, W, X, R, R, R, R, A, W, END,
            _, W, _, _, _, _, P, _, W, END,
            _, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0021 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, W, W, W, W, W, W, W, W, W, W, END,
            _, W, _, _, _, _, _, _, _, _, W, END,
            _, W, _, X, _, _, _, _, A, _, W, END,
            W, W, _, W, W, W, W, W, W, _, W, END,
            W, _, _, _, B, _, _, B, _, _, W, END,
            W, _, _, _, B, _, _, B, _, _, W, END,
            W, W, _, W, W, W, W, W, W, _, W, END,
            _, W, _, D, _, _, _, _, X, _, W, END,
            _, W, _, _, _, _, P, _, _, _, W, END,
            _, W, W, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0022 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, W, W, W, W, END,
            _, _, _, W, X, _, W, END,
            _, W, W, W, W, _, W, END,
            _, W, _, A, X, _, W, END,
            W, W, _, U, _, _, W, END,
            W, _, X, P, X, W, W, END,
            W, _, _, _, _, W, END,
            W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0023 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, END,
            W, X, _, _, B, _, W, END,
            W, W, A, L, _, _, W, END,
            _, W, W, B, P, B, W, END,
            _, _, W, _, _, _, W, END,
            _, _, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0024 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, W, END,
            W, W, W, _, _, _, _, W, W, W, END,
            W, _, X, _, _, _, _, X, _, W, END,
            W, _, _, B, B, B, B, _, _, W, END,
            W, W, _, B, _, _, B, _, W, W, END,
            W, W, _, B, _, P, B, _, W, W, END,
            W, _, _, B, B, B, B, _, _, W, END,
            W, _, R, _, _, _, _, A, _, W, END,
            W, W, W, _, _, _, _, W, W, W, END,
            _, _, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0025 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, END,
            _, _, W, _, _, _, W, END,
            W, W, W, _, W, _, W, W, W, W, W, END,
            W, _, _, _, _, _, _, _, _, _, W, END,
            W, _, W, B, W, W, W, X, W, _, W, END,
            W, _, _, _, W, P, W, _, _, _, W, END,
            W, W, W, _, W, _, A, _, W, W, W, END,
            _, _, W, _, W, _, W, _, W, END,
            _, _, W, _, W, _, _, _, W, END,
            _, _, W, _, W, W, W, W, W, END,
            _, _, W, _, _, _, W, END,
            _, _, W, _, W, _, W, END,
            _, _, W, _, U, _, W, END,
            _, _, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0026 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, END,
            _, _, W, _, _, W, END,
            _, _, W, _, X, W, W, W, W, W, END,
            _, _, W, _, _, _, _, _, _, W, END,
            W, W, W, _, W, W, _, L, _, W, END,
            W, _, A, _, W, W, _, W, W, W, END,
            W, _, _, _, _, _, P, W, END,
            W, W, W, W, W, X, _, W, END,
            _, _, _, _, W, _, _, W, END,
            _, _, _, _, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0027 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, END,
            W, _, _, X, _, X, W, END,
            W, _, L, X, _, W, W, W, END,
            W, _, _, _, _, X, P, W, END,
            W, _, U, _, L, W, W, W, END,
            W, W, W, W, A, W, END,
            _, _, _, W, _, W, END,
            _, _, _, W, U, W, END,
            _, _, _, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0028 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, END,
            _, W, W, X, X, X, W, W, END,
            W, W, _, _, _, _, _, W, W, END,
            W, X, _, D, _, L, _, X, W, END,
            W, X, _, _, A, _, _, X, W, END,
            W, X, _, R, _, U, _, X, W, END,
            W, W, _, _, P, _, _, W, W, END,
            _, W, W, X, X, X, W, W, END,
            _, _, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0029 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, _, _, _, W, W, W, W, END,
            W, W, W, W, W, _, W, _, _, W, END,
            W, _, _, _, W, W, W, L, _, W, END,
            W, _, D, _, _, X, _, _, _, W, END,
            W, W, W, _, _, _, P, _, W, W, END,
            _, _, W, X, _, A, _, X, W, END,
            _, W, W, _, _, _, _, _, W, W, W, END,
            _, W, _, _, _, X, _, _, U, _, W, END,
            _, W, _, R, W, W, W, _, _, _, W, END,
            _, W, _, _, W, _, W, W, W, W, W, END,
            _, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0030 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, W, W, W, END,
            _, _, W, _, R, _, _, _, _, W, END,
            W, W, W, _, R, A, B, B, P, W, END,
            W, _, _, _, R, _, _, _, _, W, END,
            W, _, _, _, X, U, _, W, W, W, END,
            W, W, W, W, _, X, _, W, END,
            _, _, _, W, W, _, _, W, END,
            _, _, _, _, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0031 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, END,
            W, _, P, _, W, END,
            W, X, D, X, W, W, W, W, W, END,
            W, _, W, _, W, _, _, _, W, END,
            W, _, _, _, _, _, A, _, W, END,
            W, _, _, _, W, W, W, W, W, END,
            W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0032 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, W, W, W, END,
            W, _, _, R, _, _, L, _, _, _, W, END,
            W, X, _, R, _, _, L, _, A, _, W, END,
            W, X, _, R, _, _, L, _, P, _, W, END,
            W, _, _, R, _, _, L, _, _, _, W, END,
            W, W, W, W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0033 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            W, W, W, W, W, W, W, W, END,
            W, X, _, _, _, _, X, W, END,
            W, _, _, D, D, _, _, W, END,
            W, _, R, _, _, L, _, W, END,
            W, _, R, _, A, L, _, W, END,
            W, _, R, _, _, L, _, W, END,
            W, _, P, U, U, _, _, W, END,
            W, X, _, _, _, _, X, W, END,
            W, W, W, W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0034 of\n"
        "the original 1994\n"
        "version of the game."
    },
    {
        .data = (const uint8_t[]){
            _, _, _, W, W, W, W, END,
            _, _, W, W, _, _, W, W, END,
            _, _, W, _, _, _, X, W, W, END,
            _, _, W, _, _, _, _, _, W, END,
            _, _, W, D, B, D, P, _, W, END,
            _, _, W, A, _, _, _, _, W, END,
            W, W, W, W, X, W, W, W, W, END,
            W, _, X, _, X, W, END,
            W, _, _, _, W, W, END,
            W, W, W, W, W, END,
            END,
        },
        .message =
        "This stage was\n"
        "converted from\n"
        "stage 0035 of\n"
        "the original 1994\n"
        "version of the game."
    },
