    {
        .data = (const uint8_t[]){
            _, _, W, W, W, W, W, W, W, _, _, _, _, _, _, _, END,
            _, _, W, _, _, _, _, _, W, W, W, W, W, _, _, _, END,
            _, W, W, R, W, W, W, _, W, _, _, _, W, _, _, _, END,
            _, W, _, _, _, _, A, _, W, _, P, _, W, _, _, _, END,
            _, W, _, W, _, _, X, _, _, _, W, W, W, W, _, _, END,
            _, W, _, W, _, _, D, _, W, W, _, _, _, W, W, W, END,
            W, W, _, W, _, W, W, _, W, W, _, X, _, _, _, W, END,
            W, _, _, X, _, W, W, _, W, W, _, W, W, X, _, W, END,
            W, _, _, W, W, W, W, _, _, _, _, _, W, _, _, W, END,
            W, _, _, W, _, W, W, W, _, X, _, _, W, W, W, W, END,
            W, W, W, W, _, _, _, W, _, _, U, _, W, _, _, _, END,
            _, _, _, _, _, _, _, _, W, W, W, W, W, _, _, _, END,
            END,
        },
    },
