    {
        .data = (const uint8_t[]){
            W, W, W, B, W, W, W, W, W, W, W, W, W, W, W, W, B, W, W, W, END,
            W, W, B, W, W, _, _, W, W, W, W, W, W, W, W, W, W, B, W, W, END,
            W, B, W, W, W, _, _, W, W, W, W, W, W, W, W, W, W, W, B, W, END,
            B, W, W, W, _, X, B, W, W, W, W, W, W, W, _, _, W, W, W, B, END,
            W, W, W, W, _, X, _, _, _, X, _, L, _, B, B, _, _, W, W, W, END,
            W, W, W, _, X, _, X, B, _, _, _, _, _, P, B, _, _, W, W, W, END,
            W, W, X, _, X, _, W, W, W, _, _, _, W, W, W, W, W, W, W, W, END,
            W, W, _, _, _, W, W, W, W, _, X, _, W, W, W, W, W, W, W, W, END,
            W, W, W, W, W, W, W, W, W, _, _, _, W, W, W, _, _, W, W, W, END,
            W, W, W, R, _, _, _, _, _, _, _, _, B, _, X, _, _, _, W, W, END,
            W, W, W, W, _, _, A, _, B, _, _, _, X, _, _, _, _, L, W, W, END,
            W, W, W, W, W, W, W, W, W, _, _, _, W, W, W, W, W, W, W, W, END,
            B, W, W, W, W, W, W, W, W, _, _, _, W, W, W, W, W, W, W, B, END,
            W, B, W, W, W, W, W, W, W, _, _, _, W, W, W, W, W, W, B, W, END,
            W, W, B, W, W, W, W, W, W, U, U, U, W, W, W, W, W, B, W, W, END,
            W, W, W, B, W, W, W, W, W, W, W, W, W, W, W, W, B, W, W, W, END,
            END,
        },
    },
