    {
        .data = (const uint8_t[]){
            _, _, _, _, B, B, B, B, B, B, B, B, _, END,
            _, _, _, _, B, B, B, B, B, B, B, B, _, END,
            _, _, _, _, W, W, _, _, W, W, W, W, _, END,
            _, _, _, _, W, _, A, _, _, W, W, W, _, END,
            _, _, _, _, W, _, _, W, _, _, _, W, _, END,
            _, _, _, _, W, X, X, W, W, W, _, W, _, END,
            _, _, _, _, W, _, _, P, _, X, _, W, _, END,
            _, _, _, _, W, X, W, W, W, W, _, W, _, END,
            _, _, W, W, W, _, _, _, W, _, _, _, W, END,
            _, W, _, _, _, _, X, _, W, _, X, _, W, END,
            W, W, R, _, W, _, _, _, X, _, _, W, W, END,
            W, _, _, _, W, _, X, W, W, _, _, W, W, END,
            W, _, _, _, X, _, _, W, W, W, W, W, W, END,
            _, W, W, W, W, W, W, W, _, W, W, W, _, END,
            END,
        },
        .message = "        " C_B C_P C_A C_B,
    },
