    {
        .data = (const uint8_t[]){
            _, _, _, _, W, W, W, W, W, _, _, _, _, END,
            _, _, _, _, W, _, _, _, W, W, W, W, _, END,
            _, _, _, _, W, _, D, _, _, _, _, W, W, END,
            W, W, W, W, W, _, W, W, W, W, _, _, W, END,
            W, _, _, B, _, _, W, _, _, _, W, _, W, END,
            W, _, W, X, W, _, W, _, W, _, W, _, W, END,
            W, _, W, _, P, _, _, _, _, _, W, _, W, END,
            W, _, W, _, W, W, B, W, W, W, W, _, W, END,
            W, _, _, _, W, W, _, _, _, _, B, _, W, END,
            W, _, W, A, W, W, _, W, _, W, W, W, W, END,
            W, _, _, _, _, _, _, _, _, W, _, _, _, END,
            W, W, W, W, W, W, W, W, _, W, W, W, W, END,
            _, _, _, _, _, _, _, W, _, _, _, _, W, END,
            _, _, _, _, _, _, _, W, B, _, X, _, W, END,
            _, _, _, _, _, _, _, W, _, _, W, W, W, END,
            _, _, _, _, _, _, _, W, W, W, W, _, _, END,
            END,
        },
    },
