    {
        .data = (const uint8_t[]){
            _, _, _, _, _, W, W, W, W, W, W, W, W, W, W, W, _, _, _, _, END,
            _, _, _, _, W, X, X, X, X, X, X, X, X, X, X, L, W, W, _, _, END,
            _, _, _, W, X, X, X, X, R, X, X, X, X, X, X, X, X, X, W, _, END,
            _, _, W, X, X, W, W, W, D, X, X, D, L, X, W, W, W, B, B, W, END,
            _, _, W, X, W, _, _, _, P, X, X, X, X, W, _, _, _, W, B, W, END,
            _, _, W, X, W, _, W, _, W, X, D, X, X, W, _, W, _, W, B, W, END,
            _, _, W, X, A, _, _, _, A, X, B, X, D, W, _, _, _, W, B, W, END,
            _, _, W, U, D, W, W, W, D, X, X, X, R, X, W, W, A, L, L, W, END,
            _, _, _, W, X, X, X, X, X, X, X, X, X, X, X, X, X, L, W, _, END,
            _, W, W, W, X, W, W, X, X, U, U, U, X, R, X, X, X, W, _, _, END,
            W, B, B, W, X, W, _, W, X, W, W, W, X, W, W, W, X, W, _, _, END,
            W, B, B, W, X, W, _, W, X, W, _, W, X, W, _, W, X, W, _, _, END,
            W, B, W, X, X, W, _, W, X, W, _, W, X, W, _, W, X, W, _, _, END,
            W, B, X, X, X, W, _, W, X, W, _, W, X, W, _, W, X, W, _, _, END,
            _, W, U, U, W, _, _, W, X, W, _, W, X, W, _, W, X, W, _, _, END,
            _, _, W, W, _, _, _, W, X, W, _, W, X, W, _, W, X, X, W, _, END,
            _, _, _, _, _, _, _, W, X, W, _, W, X, W, _, W, X, X, X, W, END,
            _, _, _, _, _, _, W, X, X, W, _, W, X, D, W, _, W, U, U, W, END,
            _, _, _, _, _, _, W, U, X, W, _, W, X, X, W, _, _, W, W, _, END,
            _, _, _, _, _, _, _, W, W, _, _, _, W, W, _, _, _, _, _, _, END,
            END,
        },
    },
